// src/types.ts
// Generated by `npm run typegen` after Supabase is linked
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      intercoms: {
        Row: {
          id: string
          name: string
          greeting: string
          twilio_phone: string
          concierge_phone: string
          dtmf_tone: string
          enabled: boolean
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          greeting?: string
          twilio_phone: string
          concierge_phone: string
          dtmf_tone?: string
          enabled?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          greeting?: string
          twilio_phone?: string
          concierge_phone?: string
          dtmf_tone?: string
          enabled?: boolean
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      intercom_codes: {
        Row: {
          id: string
          intercom_id: string
          code: string
          enabled: boolean
          description: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          intercom_id: string
          code: string
          enabled?: boolean
          description?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          intercom_id?: string
          code?: string
          enabled?: boolean
          description?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      schedules: {
        Row: {
          id: string
          intercom_code_id: string
          enabled: boolean
          type: string
          date: string | null
          week_day: number | null
          start_time: string
          end_time: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          intercom_code_id: string
          enabled?: boolean
          type: string
          date?: string | null
          week_day?: number | null
          start_time: string
          end_time: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          intercom_code_id?: string
          enabled?: boolean
          type?: string
          date?: string | null
          week_day?: number | null
          start_time?: string
          end_time?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      access_logs: {
        Row: {
          id: string
          intercom_id: string
          intercom_code_id: string | null
          schedule_id: string | null
          code_entered: string
          status: string
          created_at: string | null
        }
        Insert: {
          id?: string
          intercom_id: string
          intercom_code_id?: string | null
          schedule_id?: string | null
          code_entered: string
          status: string
          created_at?: string | null
        }
        Update: {
          id?: string
          intercom_id?: string
          intercom_code_id?: string | null
          schedule_id?: string | null
          code_entered?: string
          status?: string
          created_at?: string | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
